language: node_js
node_js:
  - "node"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
