language: node_js
node_js:
# FIXME: Use Node <11.11 for Jest compatibility
# See: https://github.com/facebook/jest/issues/8069
#  - 'node'
  - '11.10.1'

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
